n1,n2,n3=map(int,input().split())
if(n1<n2):
          if(n2<n3):
                     print(n3)
          else:
                     print(n2)
else:
          if(n1<n3):
                     print(n3)
          else:
                     print(n1)
