n1,n2,n3=input().split()
if(n1<n2):
          if(n2<n3):
                     print(n3)
          else:
                     print(n3)
else:
          if(n1<n3):
                     print(n3)
          else:
                     print(n1)
